name: test

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i -g pnpm && pnpm i
        name: Install dependencies
      - run: pnpm build --filter esbuild-plugin-react18-example
        name: build example app to run tests
      - name: Run unit tests
        run: pnpm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./esbuild-plugin-react18
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: esbuild-plugin-react18

      - uses: paambaati/codeclimate-action@v5.0.0
        continue-on-error: true
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ./esbuild-plugin-react18/coverage/*.xml:clover
